# Generated by Django 3.2.8 on 2021-10-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('paid_deposit', models.BooleanField(default=False)),
                ('paid_in_full', models.BooleanField(default=False)),
                ('enquiry_method', models.CharField(max_length=100)),
                ('enquiry_date', models.DateField()),
                ('enquiry_name', models.CharField(max_length=100)),
                ('enquiry_email', models.CharField(max_length=100)),
                ('set_option', models.CharField(max_length=100)),
                ('travel_cost', models.BigIntegerField()),
                ('quote', models.BigIntegerField()),
                ('event_type', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('contact_full_names', models.CharField(max_length=100)),
                ('contact_address', models.CharField(max_length=100)),
                ('contact_telephone', models.CharField(max_length=100)),
                ('song_request', models.CharField(max_length=100)),
                ('setup_info', models.CharField(max_length=100)),
                ('music_between_sets', models.CharField(max_length=100)),
                ('wedding_theme', models.CharField(max_length=100)),
                ('introduced_as', models.CharField(max_length=100)),
                ('timings', models.CharField(max_length=100)),
                ('any_other_info', models.CharField(max_length=100)),
            ],
        ),
    ]
